### PR TITLE
Adding missing default currency

### PR DESCRIPTION
**Pull request by mikewink**
This adds the defaultCurrency key/value to the default static config example.

### CODE REVIEW

**Comment by mattstein** [comment]
Thanks!

**Comment by mikewink** [comment]
Good morning Matt, 

sorry, but now that we read the currency from the config file, it's not shown in the product details field anymore. Can you see the same behaviour? Should I open a new ticket?

**Comment by mattstein** [comment]
Hi @mikewink,

That's odd. Saving `defaultCurrency` in the control panel works as expected, but specifying it in a config file does not. If you wouldn't mind opening a ticket that'd be great.

**Comment by mattstein** [comment]
Spoke too soon! My issue was with case sensitivity. `'defaultCurrency' => 'eur'` works in the static config file and the Product Details field displays as expected in an Entry layout. `'defaultCurrency' => 'EUR'`, however, does not.

Curious now what your config looks like!

**Pull request merged**
