### PR TITLE
Proposal: Adding image support

### PR DESCRIPTION
**Pull request by mikewink**
This little change adds optional image support or should this go into the additional props?

If agreed, we have to alter the docs too to reflect the change.

### CODE REVIEW

**Comment by mattstein** [comment]
I appreciate this @mikewink and I'm on the fence about it. You can use `additionalProps` right now as you suggest, and I'm just wondering if the template parameter should either...

- a) be `imageUrl` to clarify that only a URL (and not an Asset reference, for example) is expected or
- b) remain as `image` and attempt to gracefully handle an Asset reference somehow

Your change is a straightforward way of having the Twig method's interface reference Snipcart's product definition, I'm just not sure if it should be more Asset-sensitive in this case or if I'm overthinking it.

**Comment by mikewink** [comment]
I used 'image' as the key because it's the name used by Snipcart. I don't have any problem with the naming whatsoever. I would not mind being more specific. That's ultimately up to you.

**Comment by mattstein** [comment]
I'm just overthinking it out loud. I appreciate the suggestion and I'll merge+document for the next release.

**Comment by mattstein** [comment]
Updated in [1.0.5](https://github.com/workingconcept/snipcart-craft-plugin/releases/tag/1.0.5), noting this addition and clarifying _all_ options [in the docs](https://snipcart.docs.workingconcept.com/templating/fields.html#all-options).

**Pull request merged**
